export const API_GET_DATA_START = 'API_START_GET';
export const API_GET_DATA_SUCCESS = 'API_GET_DATA_SUCCESS';

export const MESSAGES_SEND_STORE_SUCCESS = 'MESSAGES_SEND_STORE_SUCCESS';
export const MESSAGES_UPDATE_STORE_SUCCESS = 'MESSAGES_UPDATE_STORE_SUCCESS';
/*
export const LOCAL_STORAGE_SAVE_SUCCESS = 'LOCAL_STORAGE_SAVE_SUCCESS';
export const GET_LOCAL_STORAGE_SUCCESS = 'GET_LOCAL_STORAGE_SUCCESS';*/
