export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';

export const MESSAGES_UPDATE_SUCCESS = 'MESSAGES_UPDATE_STORE_SUCCESS';
/*
export const LOCAL_STORAGE_SAVE_SUCCESS = 'LOCAL_STORAGE_SAVE_SUCCESS';
export const GET_LOCAL_STORAGE_SUCCESS = 'GET_LOCAL_STORAGE_SUCCESS';*/
