export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';

export const MESSAGES_UPDATE_REQUEST = 'MESSAGES_UPDATE_REQUEST';
export const MESSAGES_UPDATE_SUCCESS = 'MESSAGES_UPDATE_STORE_SUCCESS';
